/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.utica.spring.starter.jobsub;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
